services:
  tusd: # TUS server for file uploads
    image: tusproject/tusd:v2.8.0
    command: >
      -host=0.0.0.0 -port=1080
      -s3-bucket uploads
      -s3-endpoint http://minio:9000
      -s3-disable-ssl
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_REGION: us-east-1
    depends_on: [minio]
    ports:
      - "1080:1080"

  minio: # MinIO server for S3-compatible storage
    image: minio/minio:RELEASE.2025-07-18T21-56-31Z
    command: server /data --console-address ":9001" --address ":9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  mc-init: # MinIO Client initialization
    image: minio/mc:RELEASE.2025-07-16T15-35-03Z
    entrypoint: >
      /bin/sh -c "
       sleep 5 &&
       mc alias set myminio http://minio:9000 minioadmin minioadmin123 &&
       mc mb -p myminio/uploads || true
      "
    depends_on: [minio]

  db: # PostgreSQL database for task metadata
    image: postgres:16
    environment:
      POSTGRES_USER: tus
      POSTGRES_PASSWORD: tuspass
      POSTGRES_DB: tasks
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tus -d tasks"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports: ["5432:5432"]

  app: # Main application server
    build: ./app
    depends_on: [minio]
    shm_size: 64gb
    environment:
      TUS_ENDPOINT: http://tusd:1080/files
      MINIO_ENDPOINT:  http://192.168.1.26:9000 # Pretend this is a remote server
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      AWS_S3_ADDRESSING_STYLE: path
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"

volumes:
  minio_data:
  pgdata:
